Documentation
cheminfo-js/spectra-data pull request #59
Opened 2017-01-25 21:17 UTC by jobo322

2017-01-26 08:23 UTC, targos requested changes
Thank you for this. Some general comments:
- For optional parameters, please specify the default value if there is one.
- Be careful that the names of options are self-explanatory.
- Use consistent variable names in the whole project (like always `options` and not `opt` or `opts`)

2017-01-26 08:23 UTC, targos commented on src/filters/apodization.js
>  /**
please remove those header comments. They are added automatically by webstorm (this can be changed)

2017-01-26 08:23 UTC, targos commented on src/filters/fourierTransform.js
> -var fft = require('ml-fft');
it is correct to keep the require at the top level

2017-01-26 08:23 UTC, targos commented on src/jcampEncoder/JcampCreator.js
> +const Integer = {MAX_VALUE: 2e31 - 1, MIN_VALUE: -2e31};
please use `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`.

BTW 2e31 means 2*10^31. I guess you were thinking about Math.pow(2, 31).

2017-01-26 08:23 UTC, targos commented on src/jcampEncoder/JcampCreator.js
> +const version = 'Cheminfo tools, March 2016';
Please remove the date and instead use the version number from `require('../../package.json').version`

2017-01-26 08:23 UTC, targos commented on src/peakPicking/peakPicking.js
> + * @param {number} [options.integralFn] - option to chose between approx area with gaussian function or sum of the points of given range
I'm not sure what number I should put? Maybe a string would be more intuitive. The list of possible values should be in the documentation.
If there is a default value, put it after the parameter name like this: `[options.integralFn='defaultvalue']`

2017-01-26 08:23 UTC, targos commented on src/peakPicking/peakPicking.js
> + * @param {number} [options.frequencyCluster] - distance limit to clustering the peaks.
we need a better name for this one. @andcastillo

2017-01-26 08:23 UTC, targos commented on src/peakPicking/peakPicking.js
> + * @param {boolean} [options.minMaxRatio] - Threshold to determine if a given peak should be considered as a noise, bases on its relative height compared to the highest peak.
{number}. to be checked on the next lines.

2017-01-26 08:23 UTC, targos commented on src/peakPicking/peakPicking.js
> + * @param {boolean} [options.functionType] - This option allows us choose between gaussian or lorentzian function when options.optimize is true.
string again? Name it `optimizeFunction`

2017-01-26 08:23 UTC, targos commented on src/peakPicking/peaks2Ranges.js
> + * @param {Object} spectrum - SD instance
{SD}

2017-01-26 08:23 UTC, targos commented on src/range/Ranges.js
> +     * @param {Object} opt - options object
opt -> options

2017-01-26 08:23 UTC, targos commented on src/range/Ranges.js
> +     * @param {object} opt - options object to extractPeaks function
options

2017-01-26 08:23 UTC, targos commented on src/range/Ranges.js
> +     * @param {Object} opt - see the options parameter in peak2vector function documentation
options

2017-01-26 08:23 UTC, targos commented on src/range/Ranges.js
> +     * @param {Object} opt - see the options parameter in peak2vector function documentation
try to add a referenc to the peak2vector function. Something like `{@link#peak2vector}` ?

2017-01-26 08:23 UTC, targos commented on src/range/peak2Vector.js
> + * @option {number} [options.from] - one limit of given window
`@param`. same for next lines

2017-01-26 18:59 UTC, andcastillo commented on src/peakPicking/peakPicking.js
> + * @param {number} [options.integralFn] - option to chose between approx area with gaussian function or sum of the points of given range
I agree. It should be integralType and the values should be 'sum' or 'peaks' like in mestre. The default value should be 'sum'

2017-01-26 19:03 UTC, andcastillo commented on src/peakPicking/peakPicking.js
> + * @param {number} [options.frequencyCluster] - distance limit to clustering the peaks.
@targos  do you mean about the integralFn or about the frequencyCluster? 
integralFn should be renamed to integralType?

2017-01-27 10:23 UTC, targos commented
It seems the tests are failing. Can you check and fix the issues?

2017-01-30 15:15 UTC, targos approved these changes

2017-01-30 15:16 UTC, merged

2017-01-30 15:29 UTC, jobo322 commented on src/range/Ranges.js
> +     * @param {object} opt - options object to extractPeaks function
done

2017-01-30 15:29 UTC, jobo322 commented on src/range/peak2Vector.js
> + * @option {number} [options.from] - one limit of given window
done